language: php

php:
  - 5.6
  - 7.0
  - 7.1
  
sudo: false
  
before_install:
  - composer self-update

install:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    - leonardo.proietti@gmail.com
